### PR TITLE
Add address

### PR DESCRIPTION
**Pull request by plkrgol**
Homework from git lessons

### CODE REVIEW

**Comment by ziobron** [comment]
⚠️ Points for @plkrgol for task git were already granted in https://github.com/coders-school/git-checker/pull/129

**Comment by plkrgol** [comment]
Git homework

**Comment by ziobron** [comment]
@plkrgol Your solution has not passed all checks (maybe it was only a formatting-check?) and you haven't modified this Pull Request during the last 7 days. It will be automatically closed after the next 7 days if it remains untouched.

**Comment by ziobron** [comment]
We are closing this PR. If you want to fix your code and get points, please re-open it or raise a new PR

**Pull request closed without merging**
